grpc:
  client:
    dev-shiv-service:
      address: static://localhost:9000
      negotiationType: TLS
      security:
        trust-cert-collection: file:"/home/shiv/Samta deck/final-assesment/grpc-microservice-spring-boot-dev/client-service/certs/localhost.cert.pem"
#        trust-cert-collection: file:/home/shiv/Desktop/localhost.cert.pem